  name: GraalVM Community Edition build
  #on: [push, pull_request]
  on:
    pull_request:
      branches:
        - master
      types: [closed]
  jobs:
    publish-package:
      runs-on: ubuntu-latest
      needs: build
      steps:
        - name: Checkout
          uses: actions/checkout@v2

        - name: Download do artifact
          uses: actions/download-artifact@master
          with:
            name: personalprofile
            path:  ${{ github.workspace }}/target/*

        - name: Envio para o servidor
          uses: SamKirkland/FTP-Deploy-Action@v4.3.4
          with:
            server: ${{secrets.FTPSERVER}}
            username: ${{secrets.FTPUSERNAME}}
            password: ${{secrets.FTPPASSWORD}}
            server-dir: /home/github/personalprofile/